import api from './api';

const adminService = {
  getDashboard: async () => (await api.get('/api/admin/dashboard')).data,
  getStatistics: async (params = {}) => (await api.get('/api/admin/statistics', { params })).data,
  getUsers: async (params = {}) => (await api.get('/api/admin/users', { params })).data,
  createUser: async (payload) => (await api.post('/api/admin/users', payload)).data,
  updateUser: async (userId, payload) => (await api.patch(`/api/admin/users/${userId}`, payload)).data,
  deactivateUser: async (userId) => (await api.delete(`/api/admin/users/${userId}`)).data,
  resetPassword: async (userId, payload = {}) => (await api.post(`/api/admin/users/${userId}/reset-password`, payload)).data,
  resendInvitation: async (userId) => (await api.post(`/api/admin/users/${userId}/resend-invitation`)).data,
  assignCounselor: async (userId, payload) => (await api.post(`/api/admin/users/${userId}/assign-counselor`, payload)).data,
  getUniversities: async () => (await api.get('/api/admin/universities')).data,
  createUniversity: async (payload) => (await api.post('/api/admin/universities', payload)).data,
  updateUniversity: async (universityId, payload) => (await api.patch(`/api/admin/universities/${universityId}`, payload)).data,
  deactivateUniversity: async (universityId) => (await api.delete(`/api/admin/universities/${universityId}`)).data,
  getUniversityStatistics: async (universityId) => (await api.get(`/api/admin/universities/${universityId}/statistics`)).data,
  getCounselors: async () => (await api.get('/api/admin/counselors')).data,
  createCounselor: async (payload) => (await api.post('/api/admin/counselors', payload)).data,
  updateCounselor: async (counselorId, payload) => (await api.patch(`/api/admin/counselors/${counselorId}`, payload)).data,
  assignCounselorUniversity: async (counselorId, payload) => (await api.post(`/api/admin/counselors/${counselorId}/university`, payload)).data,
  deactivateCounselor: async (counselorId) => (await api.delete(`/api/admin/counselors/${counselorId}`)).data,
  getModels: async () => (await api.get('/api/admin/models')).data,
  getModelRuntimeStatus: async () => (await api.get('/api/admin/models/runtime-status')).data,
  verifyModel: async (modelId) => (await api.post(`/api/admin/models/${modelId}/verify`)).data,
  verifyRuntimeModel: async (modelId) => (await api.post(`/api/admin/models/${modelId}/verify-runtime`)).data,
  smokeTestModel: async (modelId) => (await api.get(`/api/admin/models/${modelId}/smoke-test`)).data,
  activateModel: async (modelId) => (await api.post(`/api/admin/models/${modelId}/activate`)).data,
  deactivateModel: async (modelId) => (await api.post(`/api/admin/models/${modelId}/deactivate`)).data,
  rollbackModel: async (modelId, payload = {}) => (await api.post(`/api/admin/models/${modelId}/rollback`, payload)).data,
  getResources: async (params = {}) => (await api.get('/api/admin/resources', { params })).data,
  createResource: async (payload) => (await api.post('/api/admin/resources', payload)).data,
  updateResource: async (resourceId, payload) => (await api.patch(`/api/admin/resources/${resourceId}`, payload)).data,
  approveResource: async (resourceId) => (await api.post(`/api/admin/resources/${resourceId}/approve`)).data,
  archiveResource: async (resourceId) => (await api.post(`/api/admin/resources/${resourceId}/archive`)).data,
  deleteResource: async (resourceId) => (await api.delete(`/api/admin/resources/${resourceId}`)).data,
  getSupportContacts: async (params = {}) => (await api.get('/api/admin/support-contacts', { params })).data,
  getAudit: async (params = {}) => (await api.get('/api/admin/audit', { params })).data,
  exportAudit: async () => (await api.get('/api/admin/audit', { params: { export: 'csv' }, responseType: 'text' })).data,
  getSettings: async () => (await api.get('/api/admin/settings')).data,
  updateSetting: async (settingId, payload) => (await api.patch(`/api/admin/settings/${settingId}`, payload)).data,
  getReports: async () => (await api.get('/api/admin/reports')).data,
  generateReport: async (payload) => (await api.post('/api/admin/reports', payload)).data,
  exportReport: async (reportId, format = 'csv') => (await api.get(`/api/admin/reports/${reportId}/export`, { params: { format }, responseType: format === 'csv' ? 'text' : 'json' })).data,
};

export default adminService;
